# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d73f1068a0ca378e4369d445918a3c90d464b13d2e7d215c9db6da5ee362d191821635df6572730971b3053dc94d1dc232d9c0595d1db99357d2a0380d94d48

test:
  secret_key_base: 2356d389b7e2ed0cdda80ecebd1efef9b3f8bc6bfe60a898c557e5902a843a5a10850eec31ff6ba9de3fd0afaec9807d7b8434cd135b85b0f13d9d7a1d90e004

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
